config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :book_clubs do
    resources :topics, except: :index
    resources :memberships, only: [:create, :destroy]
  end

  resources :topics, only: [] do
    resources :posts, except: :index
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  get 'dashboard' => 'dashboard#index'
  root 'welcome#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :post, presence: true
  validates :user, presence: true

  validates :body, length: { minimum: 1 }, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post
  before_action :set_comment, only: [:edit, :update, :destroy]

  # GET posts/1/comments/1/edit
  def edit
    authorize @comment
  end

  # POST posts/1/comments
  # POST posts/1/comments.json
  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to [@post.topic, @post], notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { redirect_to [@post.topic, @post], notice: 'Error. Comment failed to save.'}
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT posts/1/comments/1
  # PATCH/PUT posts/1/comments/1.json
  def update
    authorize @comment

    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to [@post.topic, @post], notice: 'Commment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE posts/1/comments/1
  # DELETE posts/1/comments/1.json
  def destroy
    authorize @comment
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to [@post.topic, @post], notice: 'Comment was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def set_post
      @post = Post.find(params[:post_id])
    end

    def set_comment
      @comment = @post.comments.find(params[:id])
    end

    def comment_params
     params.require(:comment).permit(:body)
   end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="row">
  <div class="col-10">
    <div class="comment-info">
      <p class="user-name">
        <%= comment.user.name %>
        <span class="created"><%= comment.updated_at.strftime("%b %d, %G %l:%M %p") %></span>
      </p>
    </div>
    <p class="comment-body"><%= comment.body %></p>
    <% if policy(comment).update? %>
      <small class="comment-actions">
        <%= link_to 'Edit', edit_post_comment_path(@presenter.post, comment) %> |
        <%= link_to 'Delete', [@presenter.post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: 'pull-right' %>
      </small>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="row">
  <div class="col">
      <%= form_with(model: [post, comment], local: true) do |form| %>
      <% if comment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

          <ul>
          <% comment.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :body, class: 'sr-only' %>
        <%= form.text_area(:body, class: "form-control", size: "100x5", placeholder: "Enter new comment here!")  %>
      </div>

      <div class="actions">
        <%= form.submit('Submit Comment', class: "btn btn-primary pull-right") %>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="container-fluid">
  <h1>Editing Comment</h1>

  <%= render 'form', comment: @comment, post: @post %>

  <%= link_to 'Back', topic_post_path(@post.topic, @post) %>
</div>