config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :book_clubs do
    resources :topics, except: :index
    resources :memberships, only: [:create, :destroy]
  end

  resources :topics, only: [] do
    resources :posts, except: :index
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  get 'dashboard' => 'dashboard#index'
  root 'welcome#index'
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :book_club
  belongs_to :user
  has_many :posts, dependent: :destroy

  before_save { self.topic_type ||= :general }

  validates :name, length: { minimum: 1, maximum: 100 }, presence: true

  enum topic_type: [ :general, :section ]
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_book_club
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, only: :show, raise: false
  before_action :authenticate_user!, unless: :current_book_club?,  only: :show

  # GET book_clubs/1/topics/1
  def show
  end

  # GET book_clubs/1/topics/new
  def new
    @topic = @book_club.topics.build
  end

  # GET book_clubs/1/topics/1/edit
  def edit
    authorize @topic
  end

  # POST book_clubs/1/topics
  def create
    @topic = @book_club.topics.build(topic_params)
    @topic.user = current_user

    respond_to do |format|
      if @topic.save
        format.html { redirect_to [@book_club, @topic], notice: 'Topic was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT book_clubs/1/topics/1
  def update
    authorize @topic

    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to [@book_club, @topic], notice: 'Topic was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE book_clubs/1/topics/1
  def destroy
    authorize @topic
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to book_club_path(@book_club), notice: 'Topic was successfully destroyed.' }
    end
  end

  private
    def set_book_club
      @book_club ||= BookClub.find(params[:book_club_id])
    end

    def set_topic
      @topic = @book_club.topics.find(params[:id])
    end

    def topic_params
      params.require(:topic).permit(:name, :topic_type)
    end

    def current_book_club?
      set_book_club
      @book_club.current?
    end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: [@book_club, topic], local: true) do |form| %>
      <% if topic.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

          <ul>
          <% topic.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label(:name, "Topic name: ") %>
        <%= form.text_field :name, :class => "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :topic_type, "Select type of topic:" %><br>
        <%= form.select :topic_type, Topic.topic_types.keys %>
      </div>

      <div class="actions">
        <%= form.submit(class: "btn btn-primary") %>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/edit.html.erb
<div class="container-fluid">
  <h1>Editing Topic</h1>

  <%= render 'form', topic: @topic %>

  <%= link_to 'Show', book_club_topic_path %> |
  <%= link_to 'Back', book_club_path(@book_club) %>
</div>

app/views/topics/new.html.erb
<div class="container-fluid">
  <h2>New Topic</h2>

  <%= render 'form', topic: @topic %>

  <br>
  <%= link_to 'Back', book_club_path(@book_club) %>
</div>

app/views/topics/show.html.erb
<div class="container">
  <!-- Book Club Info small -->
  <div class="row" style="padding-bottom: 20px">
    <div class="col-sm-4 col-md-3 col-lg-2">
      <%= image_tag @book_club.cover.url(:medium), :height => "225px" %>
    </div>
    <div class="col-sm-8 col-md-9 col-lg-10">
      <h2><%= @book_club.title %></h2>
      <p><em>By: <%= @book_club.author %></em></p>
      <p>Discussion Closes: <%= @book_club.end_date.strftime("%B %-d, %Y") %></p>
      <%= link_to 'Back to Book Club', book_club_path(@book_club) %> <br><br>
    </div>
  </div>

  <!-- Topic Title -->
  <div class="row">
    <div class="col">
      <table class="table">
        <tbody>
          <tr class="topic-item">
            <td class="topic-item-title">
              <h2><%= @topic.name %></h2>
              <% if policy(@topic).create_post? %>
                <div class="new-post">
                  <%= link_to 'New Post', new_topic_post_path(@topic), class: "btn btn-primary" %>
                </div>
              <% end %>
            </td>
            <td class="topic-item-actions">
              <% if policy(@topic).update? %>
                <%= link_to 'Edit Topic', edit_book_club_topic_path(@book_club, @topic) %> |
                <%= link_to 'Delete Topic', [@book_club, @topic], method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>

  <!-- Show Topic Posts -->
  <div class="container">
    <% @topic.posts.each do |post| %>
      <div class="row">
        <div class="col-10">
          <div class="post-info">
            <p class="user-name">
              <%= post.user.name %>
              <span class="created"><%= post.updated_at.strftime("%b %d, %G %l:%M %p") %></span>
            </p>
          </div>
          <div class="post-item">
            <p><%= link_to post.body,  topic_post_path(@topic, post) %></p>
            <small class="comment-count"><%= pluralize(post.comments.count, 'Comment') %></small>
          </div>
        </div>
      </div>
    <% end %>
  </div>

  <hr>

</div> <!-- end of container -->