config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :book_clubs do
    resources :topics, except: :index
    resources :memberships, only: [:create, :destroy]
  end

  resources :topics, only: [] do
    resources :posts, except: :index
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  get 'dashboard' => 'dashboard#index'
  root 'welcome#index'
end

app/models/book_club.rb
class BookClub < ApplicationRecord
  has_many :topics, dependent: :destroy
  has_many :memberships, dependent: :destroy

  has_attached_file :cover, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }
  validates_attachment_content_type :cover, content_type: /\Aimage\/.*\z/

  validates :title, length: { minimum: 1, maximum: 100 }, presence: true
  validates :author, length: { minimum: 1, maximum: 100 }, presence: true
  validates :description, length: { minimum: 10 }, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  # Return whether a giveb book_club is a currrent_club
  def current?
    (start_date..end_date).cover?(Date.today)
  end

  # Return whether a giveb book_club is an upcoming_club
  def upcoming?
    (start_date > Date.today)
  end

  # Return whether a giveb book_club is a past_club
  def past?
    (end_date < Date.today)
  end
end

app/controllers/book_clubs_controller.rb
class BookClubsController < ApplicationController
  before_action :set_book_club, only: [:show, :edit, :update, :destroy]

  skip_before_action :authenticate_user!, only: :show, raise: false
  before_action :authenticate_user!, unless: :current_book_club?, only: :show

  # GET /book_clubs
  def index
    @current = BookClub.where(':date BETWEEN start_date AND end_date', date: Date.today)
    @upcoming = BookClub.where(':date < start_date', date: Date.today)
    @past = BookClub.where(':date > end_date', date: Date.today).order(end_date: :desc).limit(50).paginate(page: params[:page], per_page: 6)
  end

  # GET /book_clubs/1
  # GET /book_clubs/1.json
  def show
    @general_topics = @book_club.topics.where("topic_type = '0'")
    @section_topics = @book_club.topics.where("topic_type = '1'")
  end

  # GET /book_clubs/new
  def new
    @book_club = BookClub.new
    authorize @book_club
  end

  # GET /book_clubs/1/edit
  def edit
    authorize @book_club
  end

  # POST /book_clubs
  def create
    @book_club = BookClub.new(book_club_params)
    authorize @book_club

    respond_to do |format|
      if @book_club.save
        format.html { redirect_to @book_club, notice: 'Book club was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /book_clubs/1
  def update
    authorize @book_club

    respond_to do |format|
      if @book_club.update(book_club_params)
        format.html { redirect_to @book_club, notice: 'Book club was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /book_clubs/1
  def destroy
    authorize @book_club
    @book_club.destroy

    respond_to do |format|
      format.html { redirect_to book_clubs_url, notice: 'Book club was successfully destroyed.' }
    end
  end

  private
    def set_book_club
      @book_club ||= BookClub.find(params[:id])
    end

    def book_club_params
      params.require(:book_club).permit(:title, :author, :description, :start_date, :end_date, :cover)
    end

    def current_book_club?
      set_book_club
      @book_club.current?
    end
end

app/helpers/book_clubs_helper.rb
module BookClubsHelper
end

app/views/book_clubs/_admin_index.html.erb
<div class="container">
  <div align="right">
    <%= link_to 'Create New Book Club', new_book_club_path, class: "btn btn-primary" %>
  </div>

  <div class="current-clubs">
    <h3>Current Book Clubs</h3>
    <%= render partial: "table", locals: { book_clubs: current } %>
  </div>

  <div class="upcoming-clubs">
    <h3>Upcoming Book Clubs</h3>
    <%= render partial: "table", locals: { book_clubs: upcoming } %>
  </div>

  <div class="past-clubs">
    <h3>Past Book Clubs</h3>
    <%= render partial: "table", locals: { book_clubs: past } %>
  </div>
  
  <div class="row justify-content-end">
    <%= will_paginate past %>
  </div>
</div> <!-- end of container -->

app/views/book_clubs/_book_tile.html.erb
<div class="col-lg-2 col-md-3 col-sm-4 book-list">
  <div class="cover">
    <%= link_to book_club_path(book_club) do %>
      <%= image_tag(book_club.cover.url(:medium), size: "150x227", alt: book_club.title) %>
    <% end %>
  </div>
  <h4 class="title"><%= book_club.title %></h4>
  <div class="by">
    <em>by: </em>
    <span><%= book_club.author %></span>
  </div>
</div>

app/views/book_clubs/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: book_club, local: true, multipart: true) do |form| %>
      <% if book_club.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(book_club.errors.count, "error") %> prohibited this book_club from being saved:</h2>

          <ul>
          <% book_club.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label(:title, "Title: ") %>
        <%= form.text_field(:title, class: "form-control")%>

        <%= form.label(:author, "Author: ") %>
        <%= form.text_field(:author, class: "form-control")  %>
      </div>

      <div class="form-group">
        <%= form.label(:description, "Description: ") %>
        <%= form.text_area(:description, size: "100x5", class: "form-control")  %>
      </div>

      <div class="form-group">
        <%= form.label(:start_date, "Start Date: ") %>
        <%= form.date_field("start_date", class: "form-control") %>

        <%= form.label(:end_date, "End Date: ") %>
        <%= form.date_field("end_date", class: "form-control") %>
      </div>

      <div class="form-group">
        <%= form.label("Cover Art: ") %>
        <%= form.file_field :cover %>
      </div>

      <div class="actions">
        <%= form.submit(class: "btn btn-primary") %>
      </div>
    <% end %>
  </div>
</div>

app/views/book_clubs/_member_index.html.erb
<div class="container">
  <!-- Current book club tiles -->
  <div class="row">
    <div class="col">
      <h3>This Month's Book Clubs</h3>
    </div>
  </div>
  <div class="member-index-catagory-container">
    <div class="row">
      <% current.each do |book_club| %>
        <%= render partial: "book_tile", locals: { book_club: book_club } %>
      <% end %>
    </div>
  </div>

  <!-- Upcoming book club tiles -->
  <div class="row">
    <div class="col">
      <h3>Coming Next Month</h3>
    </div>
  </div>
  <div class="member-index-catagory-container">
    <div class="row">
      <% upcoming.each do |book_club| %>
        <%= render partial: "book_tile", locals: { book_club: book_club } %>
      <% end %>
    </div>
  </div>

  <!-- Past book club tiles -->
  <div class="row">
    <div class="col">
      <h3>Past Book Clubs</h3>
    </div>
  </div>
  <div class="member-index-catagory-container">
    <div class="row">
      <% past.each do |book_club| %>
        <%= render partial: "book_tile", locals: { book_club: book_club } %>
      <% end %>
    </div>
    <div class="row justify-content-end">
      <%= will_paginate past %>
    </div>
  </div>

</div> <!-- end of container -->

app/views/book_clubs/_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th colspan="2"></th>
      <th colspan="1">Start Date</th>
      <th colspan="1">End Date</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% book_clubs.each do |book_club| %>
      <tr>
        <td class="bookclub-item-thumb"><%= image_tag book_club.cover.url(:thumb) %></td>
        <td class="bookclub-item-title"><%= link_to book_club.title, book_club %></td>
        <td class="bookclub-item-date"><%= book_club.start_date.strftime("%B %-d, %Y") %></td>
        <td class="bookclub-item-date"><%= book_club.end_date.strftime("%B %-d, %Y") %></td>
        <td class="bookclub-item-actions">
          <%= link_to 'Edit', edit_book_club_path(book_club) %> |
          <%= link_to 'Delete', book_club, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/book_clubs/edit.html.erb
<div class="container-fluid">
  <h2>Editing Book Club</h2>

  <%= render 'form', book_club: @book_club %>

  <br>
  <%= link_to 'Show', @book_club %> |
  <%= link_to 'Back', book_clubs_path %>
</div>

app/views/book_clubs/index.html.erb
<% if current_user.admin? %>
  <%= render partial: "admin_index", locals: { current: @current, upcoming: @upcoming, past: @past } %>
<% else %>
  <%= render partial: "member_index", locals: { current: @current, upcoming: @upcoming, past: @past } %>
<% end %>

app/views/book_clubs/new.html.erb
<div class="container-fluid">
  <h2>New Book Club</h2>

  <%= render 'form', book_club: @book_club %>

  <br>
  <%= link_to 'Back', book_clubs_path %>
</div>

app/views/book_clubs/show.html.erb
<div class="container">
  <!-- Book Club Info -->
  <div class="row book-club-info">
    <div class="col-md-5 col-lg-4" align="center">
      <%= image_tag @book_club.cover.url(:large), size: "275x412", class: "cover" %>
    </div>
    <div class="col-md-7 col-lg-8">
      <div class="title">
        <h2><%= @book_club.title %></h2>
        <% if policy(@book_club).join? %>
         <%= render partial: 'memberships/join', locals: { book_club: @book_club } %>
        <% end %>
      </div>
      <div class="author">
        <p><em>By: <%= @book_club.author %></em></p>
      </div>
      <div class="description">
        <p><%= @book_club.description %></p>
        <p>Start date: <%= @book_club.start_date.strftime("%B %-d, %Y") %></p>
        <p>Discussion Closes: <%= @book_club.end_date.strftime("%B %-d, %Y") %></p>
      </div>
      <div class="controls">
        <% if current_user %>
          <%= link_to 'Back to Bookshelf', book_clubs_path %>
        <% end %>
      </div>
    </div>
  </div>

  <hr>
  
  <!-- General Discussion -->
  <div class="row">
    <div class="col">
      <div class="title">
        <h4>General Discussion</h4>
        <% if policy(@book_club).create_topic? %>
          <%= link_to 'Add New Topic', new_book_club_topic_path(@book_club), class: "btn btn-primary" %>
        <% end %>
      </div>
      <p>Warning: Spoilers may be present here!</p>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <% @general_topics.each do |topic| %>
        <h5><%= link_to topic.name, book_club_topic_path(@book_club, topic) %></h5>
        <p><%= pluralize(topic.posts.count, 'Post') %></p>
      <% end %>
    </div>
  </div>

  <hr>

  <!-- Section Discussion -->
  <div class="row">
    <div class="col">
      <h4>Section Discussion</h4>
      <p>Just finished a chapter and want to talk about it?</p>
      <% @section_topics.each do |topic| %>
        <h5><%= link_to topic.name,  book_club_topic_path(@book_club, topic) %></h5>
        <p><%= pluralize(topic.posts.count, 'Post') %></p>
      <% end %>
    </div>
  </div>

  <hr>

</div> <!-- end of container -->