config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :book_clubs do
    resources :topics, except: :index
    resources :memberships, only: [:create, :destroy]
  end

  resources :topics, only: [] do
    resources :posts, except: :index
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :edit, :update, :destroy]
  end

  get 'dashboard' => 'dashboard#index'
  root 'welcome#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :topic
  belongs_to :user

  has_many :comments, dependent: :destroy

  validates :topic, presence: true
  validates :user, presence: true

  validates :body, length: { minimum: 1 }, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!

  # GET topics/1/posts/1
  # GET topics/1/posts/1.json
  def show
    topic = Topic.find(params[:topic_id])
    post = topic.posts.find(params[:id])
    @presenter = PostsShowPresenter.new(topic, post)
  end

  # GET topics/1/posts/new
  def new
    topic = Topic.find(params[:topic_id])
    @post = topic.posts.build
  end

  # GET topics/1/posts/1/edit
  def edit
    topic = Topic.find(params[:topic_id])
    @post = topic.posts.find(params[:id])
    authorize @post
  end

  # POST topics/1/posts
  # POST topics/1/posts.json
  def create
    topic = Topic.find(params[:topic_id])
    @post = topic.posts.build(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to [topic, @post], notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT topics/1/posts/1
  # PATCH/PUT topics/1/posts/1.json
  def update
    topic = Topic.find(params[:topic_id])
    @post = topic.posts.find(params[:id])
    authorize @post

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to [topic, @post], notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE topics/1/posts/1
  # DELETE topics/1/posts/1.json
  def destroy
    topic = Topic.find(params[:topic_id])
    @post = topic.posts.find(params[:id])
    authorize @post

    @post.destroy
    respond_to do |format|
      format.html { redirect_to book_club_topic_path(topic.book_club, topic), notice: 'Post was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    def post_params
      params.require(:post).permit(:body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="row">
  <div class="col-md-6">
    <%= form_with(model: [@post.topic, post], local: true) do |form| %>
      <% if post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area(:body, id: :post_body, class: "form-control", size: "100x5")  %>
      </div>

      <div class="actions">
        <%= form.submit(class: "btn btn-primary") %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container-fluid">
  <h1>Editing Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', topic_post_path(@post.topic, @post) %>
</div>

app/views/posts/new.html.erb
<div class="container-fluid">
  <h1>New Post</h1>

  <%= render 'form', post: @post %>

  <%= link_to 'Back', book_club_topic_path(@post.topic.book_club, @post.topic) %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <!-- Book Club Info small -->
  <div class="row">
    <div class="col-sm-4 col-md-3 col-lg-2">
      <%= image_tag @presenter.book_club_cover_url, :height => "225px" %>
    </div>
    <div class="col-sm-8 col-md-9 col-lg-10">
      <h2><%= @presenter.book_club_title %></h2>
      <p><em>By: <%= @presenter.book_club_author %></em></p>
      <p>Discussion Closes: <%= @presenter.book_club_end_date %></p>
      <br>
    </div>
  </div>

  <hr>
  <!-- Post -->
  <div class="row">
    <div class="col-sm-10">
      <h5>
        <strong><%= @presenter.topic.name %></strong>
      </h5>

      <p>
        <%= @presenter.post.body %>
      </p>
    </div>
    <div class="col-sm-2">
      <% if policy(@presenter.post).update? %>
        <%= link_to 'Edit Post', edit_topic_post_path(@presenter.topic, @presenter.post) %> |
        <%= link_to 'Delete Post', [@presenter.topic, @presenter.post], method: :delete, data: { confirm: 'Are you sure?' } %> |
      <% end %>
      <%= link_to 'Back to Topics', book_club_topic_path(@presenter.book_club, @presenter.topic) %>
    </div>
  </div>

  <!-- Comments -->
  <% if @presenter.post.comments.count > 0 %>
    <div class="container">
      <h6>Comments:</h6>
      <%= render @presenter.post.comments %>
    </div
  <% else %>
    <h6>No comments yet.</h6>
  <% end %>

  <!-- Add Comment -->
  <% if @presenter.book_club.current? %>
    <div class="row">
      <div class="col-10">
        <br>
        <h6>Add a new comment:</h6>
        <%= render 'comments/form', comment: Comment.new, post: @presenter.post %>
      </div>
    </div>
  <% end %>

</div> <!-- end of container -->